### ISSUE TITLE
Tool: ACGTraversal won't let me select source

### ISSUE THREAD

**Issue by udonink** [nfigay/ArchiCG#2]
Make selection the source does not work.
The field 'Id' is not shown as well.
![issue01-selectSource](https://github.com/user-attachments/assets/cd314276-9d28-4de6-bfc1-ccf1a3439e80)

**Comment by nfigay** [comment]
Yes, it will also be put on the backlog.
There were some regression issues when I migrated from W2UI 1 to 2.
I will very quickly address this

**Comment by nfigay** [comment]
I made the correction on the tool pane in order to have the source field displayed and useable?
