### ISSUE TITLE
Filtering edges using palette does not work

### ISSUE THREAD

**Issue by udonink** [nfigay/ArchiCG#3]
While it is working well to filter nodes, filtering of edges does not work

![issue02-filterEdge](https://github.com/user-attachments/assets/475f72f2-6d1f-4ef3-952f-b3dae3353d26)

**Comment by nfigay** [comment]
Corrected by considering type property for edges is called edgeType, which should be used for hidding/showing,

**Comment by nfigay** [comment]
Now filtering works for edges, but also for specializations of archimate
